version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fightstars-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: fightstars
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fightstars-net

volumes:
  mysql-data:

networks:
  fightstars-net:
